### PR TITLE
Django 1.9

### PR DESCRIPTION
**Pull request by juliusosokinas**
geokey-sapelli cannot use Django 1.8 due to the requirements implementation, which then comes from GeoKey requiring Django===1.8.8.

We can't set Django>=1.8 on GeoKey as proposed, because it will then satisfy Django future releases of Django (let's say 1.10 or 2.0), but not sure if all adjustments will be done on GeoKey side to support those future releases.

Any thoughts?

### CODE REVIEW

**Comment by mstevens83** [comment]
Not sure, I fully understand. I'll have a look soon.

**Comment by mstevens83** [comment]
This can be merged into master now. If you're okay with it I'll release it as 0.7.3.

**Comment by juliusosokinas** [comment]
Not really happy with this.

The reason I install GeoKey on Travis CI because I want to create a multi scenario for the future GeoKey releases, so that extension would be tested with 0.9, 0.10, 0.11 etc.

**Comment by mstevens83** [comment]
I see, I'll put but the explicit geokey installation in the travis script then.

**Comment by mstevens83** [comment]
Done, and everything still works.

**Pull request merged**
